### ISSUE TITLE
HTTP instead of HTTPS on generated tasks

### ISSUE THREAD

**Issue by pelayomartinez** [google/creative-screenshots#4]
Hi there,
There seems to be a bit of an issue when I'm running this. Whenever one of the main functions (list-advertisers, list-placements, etc) creates its set of tasks in one of the task queues, it creates them as HTTP requests. However, only HTTPS requests seem to work under this solution. 

Everything else works fine, so if I run the requests manually with Postman to the https:// address, they will work, but they don't propagate (i.e. I can send a list-placements job and it will list placements and create generate-tags jobs, but these won't actually do anything because they are address to the http:// address.

Any clues?

**Comment by HalleyInteractive** [comment]
I'll see if updating the @google-cloud/tasks package helps, this seems to now have come out of beta.

**Comment by HalleyInteractive** [comment]
It seems to do with the authentication of the cloud task http request, without authentication it automatically reverts back to https. Sending the OIDC Token on the Cloud Task HTTP Request seems to fix this, I'm working on this in a [separate branch](https://github.com/google/creative-screenshots/tree/npm-package-upgrade).

It will require a couple more IAM roles for the service account:
- Service Account User
- Cloud Run Invoker
- Storage Object Viewer
